# Generated by Django 5.0.2 on 2024-09-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(default="default.png", upload_to="profile_pics"),
        ),
    ]
