# Generated by Django 5.0.6 on 2024-09-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='default-profile.png', upload_to='profile_pics'),
        ),
    ]
