# Generated by Django 5.0.2 on 2024-09-22 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_expense"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Expense",
        ),
    ]
